## RL hyper parameters
B: 1

# Dataset details
dataset: camelyon16
nas_root: /mnt/nas/Dataset
fglobal: 'mlp'

## pretrained backbone
backbone: 'ViT-S/16'   #'ResNet_50' 'ViT-S/16'
pretrain: 'medical_ssl' #natural_supervised medical_ssl
D_feat: 384
D_inner: 128
only_ce_as_reward: True


# Model weights -
frac_visit: 0.2
cosine_threshold: 0.95
classifier_ckpt_path:         # HAFED classifier ckpt path
classifier_ckpt_path: sasha_outputs/logs/camelyon_hafed/models/DEBUG/checkpoint-best.pt
mlp_fglobal_ckpt : sasha_outputs/logs/camelyon_tsu/models/DEBUG/checkpoint-best.pt
level1_path: sasha_outputs/features/intermediate_hafed
level3_path: sasha_outputs/features/lr/h5_files
rl_ckpt_path: sasha_outputs/logs/camelyon_rl/cosine_0.95_frac_0.2_seed_4/models/DEBUG/checkpoint-best.pt

# Extra Hyper params
n_worker: 8
pin_memory: False
n_shot: -1
dim_reduction: False